### ISSUE TITLE
创建输出文件失败

### ISSUE THREAD

**Issue by mssky9527** [Taonn/EmailAll#3]
师傅在mac上使用时会出现 with open(path, 'r', errors='ignore') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'XXXX.com_All.json'的报错，我看了下好像是你在result目录中新建了一个和域名相关的文件夹，但是我的不能创建，我后来就盖output.py的文件，改写了之后不让他在下面创建文件夹了，直接输出到result目录中，但是改了之后还是不能运行成功，师傅能看看是什么原因吗

**Comment by Taonn** [comment]
> 师傅在mac上使用时会出现 with open(path, 'r', errors='ignore') as f: FileNotFoundError: [Errno 2] No such file or directory: 'XXXX.com_All.json'的报错，我看了下好像是你在result目录中新建了一个和域名相关的文件夹，但是我的不能创建，我后来就盖output.py的文件，改写了之后不让他在下面创建文件夹了，直接输出到result目录中，但是改了之后还是不能运行成功，师傅能看看是什么原因吗

这边还没遇到过这种情况 看报错 估计是没有这个文件导致的
